package:
  name: forecastblurdenoise
  version: 0.1.0

source:
  git_url: https://github.com/SepKfr/forecast_blur_denoise
  git_tag: 0.1.0

build:
  number: 0
  noarch: python
  script: python -m pip install .

requirements:
  build:
    - python
    - pip
  run:
    - python >=3.10
    - torch >=2.0.1
    - gpytorch >=1.9.0
    - pandas >=1.5.2
    - numpy >=1.23.5
    - optuna >=3.3.0

about:
  home: https://github.com/SepKfr/forecast_blur_denoise
  license: MIT  # Replace with the actual license
  license_file: LICENSE  # Replace with the actual license file

test:
  imports:
    - forecastblurdenoise

