package:
  name: forecastblurdenoise
  version: '1.0.3'

source:
  git_url: https://github.com/SepKfr/Fine_grained_forecasting.git

build:
  number: 0
  noarch: python
  script: python -m pip install .

requirements:
  build:
    - python
    - pip
  run:
    - python >=3.9

about:
  home: https://github.com/SepKfr/Fine_grained_forecasting.git
  license: MIT  # Replace with the actual license
  license_file: LICENSE  # Replace with the actual license file

test:
  imports:
    - forecastblurdenoise

